# Generated by Django 5.0.1 on 2024-01-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('agency', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=50)),
                ('charge', models.CharField(max_length=200)),
                ('statute', models.CharField(max_length=200)),
                ('arrest_type', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('arrest_date', models.DateField(blank=True, null=True)),
                ('arrest_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
