# Generated by Django 5.0.1 on 2024-01-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrests_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrestrecord',
            name='defendant_lawyer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='arrestrecord',
            name='state_lawyer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
